# Generated by Django 4.1.2 on 2022-11-02 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sportsCategory',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('sportsName', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('urls', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='sportsCategory/')),
                ('addDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sportsPost',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('postName', models.TextField(max_length=50)),
                ('content', models.TextField()),
                ('urls', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='sportsPost/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practiceApp.sportscategory')),
            ],
        ),
    ]
